"use client";

import Link from "next/link";
import { useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, CalendarDays, CreditCard, Mail, MapPin, Pencil, Phone, RefreshCw, Trash2, UserRound } from "lucide-react";
import { api } from "@/lib/api";
import { formatCurrency, formatDate, getErrorMessage, initials } from "@/lib/utils";
import { useApiQuery } from "@/hooks/use-api-query";
import { useLocale } from "@/components/locale-provider";
import { useAuth } from "@/components/auth-provider";
import { useToast } from "@/components/toast-provider";
import { MemberFormDialog, RenewMemberDialog } from "@/components/forms/member-form";
import { PaymentFormDialog } from "@/components/forms/payment-form";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog } from "@/components/ui/dialog";
import { EmptyState, ErrorState, PageLoading } from "@/components/ui/states";
import { StatusBadge } from "@/components/ui/status-badge";

export default function MemberDetailsPage() {
  const params = useParams<{ id: string }>(); const router = useRouter(); const { t, locale } = useLocale(); const { can } = useAuth(); const { toast } = useToast();
  const { data: member, error, loading, reload } = useApiQuery(() => api.members.get(params.id), [params.id]);
  const [editOpen, setEditOpen] = useState(false); const [renewOpen, setRenewOpen] = useState(false); const [paymentOpen, setPaymentOpen] = useState(false); const [deleteOpen, setDeleteOpen] = useState(false); const [deleting, setDeleting] = useState(false);
  if (loading && !member) return <PageLoading />;
  if (error || !member) return <ErrorState title="Could not load member" message={error?.message ?? "Member not found."} onRetry={reload} />;
  const remove = async () => { setDeleting(true); try { await api.members.remove(member.id); toast("Member deleted"); router.replace("/members"); } catch (caught) { toast("Could not delete member", { description: getErrorMessage(caught), tone: "error" }); setDeleting(false); } };
  return <div className="space-y-5 animate-fade-up"><div className="flex flex-col gap-4"><Link href="/members" className="inline-flex w-fit items-center gap-2 text-xs font-semibold text-secondary hover:text-primary"><ArrowLeft className="size-4 rtl:rotate-180" />{t("members.title")}</Link><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-center gap-4"><div className="flex size-14 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-primary to-primary-hover text-lg font-black text-[#04200f]">{initials(member.fullName)}</div><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-extrabold sm:text-[28px]">{member.fullName}</h1><StatusBadge status={member.membershipStatus} /></div><p className="mt-1 font-mono text-[11px] text-muted">{member.memberId}</p></div></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => setEditOpen(true)}><Pencil className="size-4" />{t("common.edit")}</Button><Button variant="secondary" onClick={() => setPaymentOpen(true)}><CreditCard className="size-4" />{t("members.recordPayment")}</Button><Button onClick={() => setRenewOpen(true)}><RefreshCw className="size-4" />{t("members.renew")}</Button>{can("OWNER", "ADMIN") && <Button variant="danger" size="icon" onClick={() => setDeleteOpen(true)} aria-label={t("common.delete")}><Trash2 className="size-4" /></Button>}</div></div></div>
    <section className="grid gap-3 md:grid-cols-3"><SummaryTile label="Current plan" value={member.planName} icon={<UserRound />} /><SummaryTile label="Membership expires" value={formatDate(member.expiryDate, locale)} icon={<CalendarDays />} tone={member.membershipStatus === "Expired" ? "danger" : member.membershipStatus === "Expiring Soon" ? "warning" : "green"} /><SummaryTile label="Outstanding balance" value={formatCurrency(member.balance ?? 0, locale)} icon={<CreditCard />} tone={(member.balance ?? 0) > 0 ? "warning" : "green"} /></section>
    <section className="grid gap-3 xl:grid-cols-[.8fr_1.2fr]"><Card className="p-5"><h2 className="text-sm font-bold">{t("members.contact")}</h2><dl className="mt-5 space-y-4"><Info icon={<Phone />} label={t("common.phone")} value={member.phone} dir="ltr" /><Info icon={<Mail />} label={t("common.email")} value={member.email || "Not provided"} dir="ltr" /><Info icon={<UserRound />} label="CNIC / ID" value={member.cnic || "Not provided"} dir="ltr" /><Info icon={<CalendarDays />} label="Date of birth" value={formatDate(member.dateOfBirth, locale)} /><Info icon={<MapPin />} label="Address" value={member.address || "Not provided"} /></dl>{member.notes && <div className="mt-5 border-t border-white/[.07] pt-4"><p className="text-[10px] uppercase tracking-wider text-muted">{t("common.notes")}</p><p className="mt-2 text-xs leading-relaxed text-secondary">{member.notes}</p></div>}</Card><Card className="p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-bold">{t("members.membership")}</h2><StatusBadge status={member.paymentStatus} /></div><dl className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-3"><CompactInfo label={t("members.joinDate")} value={formatDate(member.joinDate, locale)} /><CompactInfo label={t("members.startDate")} value={formatDate(member.startDate, locale)} /><CompactInfo label={t("members.expiryDate")} value={formatDate(member.expiryDate, locale)} /><CompactInfo label={t("members.fee")} value={formatCurrency(member.fee, locale)} /><CompactInfo label={t("members.discount")} value={formatCurrency(member.discount ?? 0, locale)} /><CompactInfo label={t("members.finalFee")} value={formatCurrency(member.finalFee ?? 0, locale)} /><CompactInfo label="Amount paid" value={formatCurrency(member.amountPaid ?? 0, locale)} /><CompactInfo label="Balance" value={formatCurrency(member.balance ?? 0, locale)} /></dl></Card></section>
    <Card className="overflow-hidden"><div className="border-b border-white/[.07] px-5 py-4"><h2 className="text-sm font-bold">{t("members.paymentHistory")}</h2></div><div className="p-4">{member.paymentHistory?.length ? <div className="overflow-x-auto"><table className="min-w-[760px] w-full text-xs"><thead><tr className="bg-white/[.05] text-[10px] uppercase text-muted"><th className="rounded-s-lg px-3 py-3 text-start">{t("common.date")}</th><th className="px-3 py-3 text-start">Payment ID</th><th className="px-3 py-3 text-start">{t("common.amount")}</th><th className="px-3 py-3 text-start">{t("payments.method")}</th><th className="px-3 py-3 text-start">{t("payments.balance")}</th><th className="rounded-e-lg px-3 py-3 text-start">{t("common.status")}</th></tr></thead><tbody>{member.paymentHistory.map((payment) => <tr key={payment.id} className="border-b border-white/[.055]"><td className="px-3 py-3 text-secondary">{formatDate(payment.date, locale)}</td><td className="px-3 py-3 font-mono text-[10px] text-muted">{payment.paymentId}</td><td className="px-3 py-3 font-semibold">{formatCurrency(payment.amountPaid, locale)}</td><td className="px-3 py-3 text-secondary">{payment.method}</td><td className="px-3 py-3 text-secondary">{formatCurrency(payment.balance, locale)}</td><td className="px-3 py-3"><StatusBadge status={payment.status} /></td></tr>)}</tbody></table></div> : <EmptyState title="No payments recorded" description="New payment records for this member will appear here." action={<Button size="sm" onClick={() => setPaymentOpen(true)}>{t("members.recordPayment")}</Button>} />}</div></Card>
    <Card className="overflow-hidden"><div className="border-b border-white/[.07] px-5 py-4"><h2 className="text-sm font-bold">{t("members.renewalHistory")}</h2></div><div className="p-4">{member.renewalHistory?.length ? <div className="grid gap-3 md:grid-cols-2">{member.renewalHistory.map((renewal) => <article key={renewal.id} className="rounded-xl border border-white/[.07] bg-white/[.02] p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold">{renewal.previousPlan} <span className="mx-1 text-primary">→</span> {renewal.newPlan}</p><span className="text-[10px] text-muted">{formatDate(renewal.renewalDate, locale)}</span></div><div className="mt-3 flex justify-between text-[11px] text-secondary"><span>New expiry: {formatDate(renewal.newExpiryDate, locale)}</span><strong className="text-foreground">{formatCurrency(renewal.amountPaid, locale)}</strong></div></article>)}</div> : <EmptyState title="No membership renewals" description="The complete renewal trail is retained instead of overwriting history." />}</div></Card>
    <MemberFormDialog open={editOpen} member={member} onClose={() => setEditOpen(false)} onSaved={reload} /><RenewMemberDialog open={renewOpen} member={member} onClose={() => setRenewOpen(false)} onSaved={reload} /><PaymentFormDialog open={paymentOpen} member={member} onClose={() => setPaymentOpen(false)} onSaved={() => reload()} />
    <Dialog open={deleteOpen} onClose={() => setDeleteOpen(false)} title={t("members.deleteTitle")} description={t("members.deleteHint")} size="sm" footer={<><Button variant="secondary" onClick={() => setDeleteOpen(false)}>{t("common.cancel")}</Button><Button variant="danger" loading={deleting} onClick={remove}><Trash2 className="size-4" />{t("common.delete")}</Button></>}><p className="text-sm text-secondary">Delete <strong className="text-foreground">{member.fullName}</strong>? Related financial records remain available to the audit system.</p></Dialog>
  </div>;
}

function SummaryTile({ label, value, icon, tone = "green" }: { label: string; value: string; icon: React.ReactNode; tone?: "green" | "warning" | "danger" }) { return <Card className="flex items-center gap-3 p-4"><span className={`flex size-10 items-center justify-center rounded-xl ${tone === "green" ? "bg-primary/10 text-primary" : tone === "warning" ? "bg-warning/10 text-warning" : "bg-danger/10 text-danger"}`}>{icon}</span><div><p className="text-[10px] text-muted">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div></Card>; }
function Info({ icon, label, value, dir }: { icon: React.ReactNode; label: string; value: string; dir?: "ltr" }) { return <div className="flex items-start gap-3"><span className="mt-0.5 text-primary [&>svg]:size-4">{icon}</span><div><dt className="text-[10px] text-muted">{label}</dt><dd className="mt-1 text-xs text-secondary" dir={dir}>{value}</dd></div></div>; }
function CompactInfo({ label, value }: { label: string; value: string }) { return <div><dt className="text-[10px] text-muted">{label}</dt><dd className="mt-1 text-xs font-semibold text-foreground">{value}</dd></div>; }
