"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import {
  AlertTriangle, ArrowDownRight, ArrowUpRight, Banknote, BarChart3, Clock3, CreditCard,
  MessageSquareText, TrendingUp, UserPlus, Users,
} from "lucide-react";
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart,
  ResponsiveContainer, Tooltip, XAxis, YAxis,
} from "recharts";
import { api } from "@/services";
import { cn, formatCurrency, formatDate } from "@/lib/utils";
import { useApiQuery } from "@/hooks/use-api-query";
import { useLocale } from "@/components/locale-provider";
import { useAuth } from "@/components/auth-provider";
import { Card } from "@/components/ui/card";
import { Select } from "@/components/ui/form-controls";
import { ErrorState } from "@/components/ui/states";
import { StatusBadge } from "@/components/ui/status-badge";
import type { DashboardData, DistributionPoint, GymSection } from "@/types/api";

const colors = ["#32E875", "#38A9FF", "#9565F6", "#F5B942", "#FF5252", "#93A1AA"];

function StatCard({ icon, value, label, change, detail, tone = "green", currency }: { icon: ReactNode; value: number; label: string; change: number; detail: string; tone?: "green" | "amber" | "red" | "blue" | "purple"; currency?: boolean }) {
  const { locale } = useLocale(); const positive = change >= 0;
  const toneClasses = { green: "border-primary/30 from-primary/[.10] text-primary", amber: "border-warning/30 from-warning/[.10] text-warning", red: "border-danger/30 from-danger/[.10] text-danger", blue: "border-info/30 from-info/[.10] text-info", purple: "border-purple/30 from-purple/[.10] text-purple" };
  return <Card className={cn("group relative min-h-[104px] overflow-hidden border bg-gradient-to-br to-transparent p-3 transition hover:-translate-y-0.5 hover:border-opacity-70 sm:min-h-[132px] sm:p-4", toneClasses[tone])}><div className="absolute -end-10 -top-10 size-24 rounded-full bg-current opacity-[.035] blur-xl" /><div className="relative flex h-full flex-col"><div className="flex size-8 items-center justify-center rounded-lg bg-current/15 shadow-[inset_0_0_0_1px_currentColor] [&>svg]:size-4 sm:size-10 sm:rounded-xl sm:[&>svg]:size-5">{icon}</div><div className="mt-2 flex items-end justify-between gap-1 sm:mt-3 sm:gap-2"><div className="min-w-0"><p className="truncate text-lg font-extrabold leading-none tracking-tight text-foreground sm:text-[22px]">{currency ? formatCurrency(value, locale) : new Intl.NumberFormat(locale === "ur" ? "ur-PK" : "en-PK").format(value)}</p><p className="mt-1 truncate text-[11px] font-medium text-white/85 sm:mt-2 sm:text-xs">{label}</p></div><span className={cn("mb-0.5 flex shrink-0 items-center gap-0.5 text-[9px] font-bold sm:text-[10px]", positive ? "text-primary" : "text-danger")}>{positive ? <ArrowUpRight className="size-3" /> : <ArrowDownRight className="size-3" />}{Math.abs(change)}%</span></div><p className="mt-1 hidden text-[10px] text-muted min-[380px]:block">{detail}</p></div></Card>;
}

function ChartCard({ title, icon, actions, children, className }: { title: string; icon: ReactNode; actions?: ReactNode; children: ReactNode; className?: string }) {
  return <Card className={cn("min-w-0 overflow-hidden p-3 sm:p-3.5", className)}><div className="mb-1.5 flex min-h-7 items-center justify-between gap-2 sm:mb-3 sm:min-h-8 sm:gap-3"><div className="flex min-w-0 items-center gap-1.5 text-xs font-bold sm:gap-2 sm:text-sm"><span className="shrink-0 text-foreground [&>svg]:size-4">{icon}</span><h2 className="truncate">{title}</h2></div>{actions}</div>{children}</Card>;
}

function ChartTooltip({ active, payload, label, currency = true }: { active?: boolean; payload?: Array<{ color?: string; name?: string; value?: number }>; label?: string; currency?: boolean }) {
  const { locale } = useLocale(); if (!active || !payload?.length) return null;
  return <div className="max-w-[calc(100vw-3rem)] rounded-lg border border-white/10 bg-elevated/95 px-2 py-1.5 shadow-xl backdrop-blur sm:max-w-none sm:px-3 sm:py-2"><p className="mb-0.5 text-[10px] font-semibold text-secondary sm:mb-1">{label}</p>{payload.map((entry) => <div key={entry.name} className="flex min-w-0 items-center justify-between gap-2 text-[10px] sm:min-w-32 sm:gap-4"><span className="flex min-w-0 items-center gap-1.5 text-secondary"><span className="size-1.5 shrink-0 rounded-full" style={{ background: entry.color }} /><span className="truncate">{entry.name}</span></span><strong className="shrink-0 text-foreground">{currency ? formatCurrency(Number(entry.value), locale) : new Intl.NumberFormat(locale === "ur" ? "ur-PK" : "en-PK").format(Number(entry.value))}</strong></div>)}</div>;
}

function DonutPanel({ title, data, totalLabel = "Total", pie = false }: { title: string; data: DistributionPoint[]; totalLabel?: string; pie?: boolean }) {
  const total = data.reduce((sum, item) => sum + item.value, 0);
  return <ChartCard title={title} icon={<CreditCard />}><div className="dashboard-donut-layout grid min-h-[120px] grid-cols-[minmax(112px,.8fr)_1.2fr] items-center gap-2 sm:min-h-[130px] sm:grid-cols-[minmax(120px,.75fr)_1.2fr]"><div className="dashboard-donut-chart relative h-[116px] sm:h-[125px]"><ResponsiveContainer width="100%" height="100%"><PieChart className="scale-[1.12] sm:scale-100"><Pie data={data} dataKey="value" nameKey="name" innerRadius={pie ? 0 : 39} outerRadius={56} paddingAngle={pie ? 0 : 1} stroke="none" isAnimationActive>{data.map((_, index) => <Cell key={index} fill={colors[index % colors.length]} />)}</Pie><Tooltip content={<ChartTooltip currency={false} />} /></PieChart></ResponsiveContainer>{!pie && <div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="text-[10px] text-secondary">{totalLabel}</span><strong className="text-xl font-extrabold">{total}</strong></div>}</div><div className="space-y-1.5 sm:space-y-2.5">{data.map((item, index) => <div key={item.name} className="grid grid-cols-[auto_1fr_auto] items-center gap-1.5 text-[10px] sm:gap-2"><span className="size-2.5 rounded-full" style={{ backgroundColor: colors[index % colors.length] }} /><span className="truncate text-secondary">{item.name}</span><strong className="whitespace-nowrap text-foreground">{item.value} <span className="font-normal text-muted">({total ? Math.round(item.value / total * 100) : 0}%)</span></strong></div>)}</div></div></ChartCard>;
}

function DashboardSkeleton() {
  return <div className="space-y-3"><div className="h-28 animate-pulse rounded-panel bg-white/[.045]" /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-32 animate-pulse rounded-panel bg-white/[.045]" />)}</div><div className="grid gap-3 xl:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-60 animate-pulse rounded-panel bg-white/[.045]" />)}</div></div>;
}

function SectionSelector({ value, onChange }: { value: GymSection; onChange: (section: GymSection) => void }) {
  const { t } = useLocale();
  const items: Array<{ value: GymSection; mobile: string; desktop: string; selected: string }> = [
    { value: "all", mobile: t("dashboard.wholeGym"), desktop: t("dashboard.wholeGym"), selected: "border-primary bg-primary/15 text-primary shadow-[0_0_20px_rgba(50,232,117,.12)]" },
    { value: "gents", mobile: t("dashboard.gents"), desktop: t("dashboard.gentsSection"), selected: "border-info bg-info/15 text-info shadow-[0_0_20px_rgba(56,169,255,.12)]" },
    { value: "ladies", mobile: t("dashboard.ladies"), desktop: t("dashboard.ladiesSection"), selected: "border-[#ff4fa3] bg-[#ff4fa3]/15 text-[#ff75b8] shadow-[0_0_20px_rgba(255,79,163,.12)]" },
  ];
  return <section className="grid grid-cols-3 gap-1.5 sm:gap-3" aria-label={t("dashboard.sectionFilter")}>
    {items.map((item) => <button key={item.value} type="button" aria-pressed={value === item.value} onClick={() => onChange(item.value)} className={cn("min-w-0 rounded-xl border border-white/[.08] bg-card px-1.5 py-2.5 text-[11px] font-bold text-secondary transition hover:border-white/20 hover:text-white sm:px-4 sm:py-3 sm:text-sm", value === item.value && item.selected)}><span className="sm:hidden">{item.mobile}</span><span className="hidden sm:inline">{item.desktop}</span></button>)}
  </section>;
}

export function DashboardPage() {
  const { t, locale } = useLocale(); const { user } = useAuth(); const [range, setRange] = useState("6months"); const [section, setSection] = useState<GymSection>("all");
  const ownerSection = user?.role === "OWNER" ? section : "all";
  const { data, error, loading, reload } = useApiQuery(() => api.dashboard(range, ownerSection), [range, ownerSection]);
  if (loading && !data) return <DashboardSkeleton />;
  if (error && !data) return <ErrorState title="Could not load dashboard" message={error.message} onRetry={reload} />;
  const dashboard = data as DashboardData;
  const memberLabel = ownerSection === "gents" ? t("dashboard.gentsMembers") : ownerSection === "ladies" ? t("dashboard.ladiesMembers") : t("dashboard.totalMembers");
  const activeLabel = ownerSection === "gents" ? t("dashboard.activeGents") : ownerSection === "ladies" ? t("dashboard.activeLadies") : t("dashboard.activeMembers");
  const filter = <Select value={range} onChange={(event) => setRange(event.target.value)} className="dashboard-chart-filter h-8 w-[104px] min-w-0 shrink-0 px-2 py-0 text-[10px] sm:w-auto sm:min-w-28 sm:px-3" aria-label="Chart period"><option value="6months">{t("dashboard.last6Months")}</option><option value="12m">{t("dashboard.last12Months")}</option><option value="year">{t("dashboard.thisYear")}</option></Select>;
  return <div className="space-y-3 animate-fade-up">
    <section className="relative min-h-[112px] overflow-hidden rounded-panel border border-white/[.07] bg-[url('/images/fitx-hero.png')] bg-cover bg-[center_38%] px-4 py-5 sm:px-6 sm:py-6"><div className="absolute inset-0 bg-gradient-to-r from-[#060b0e] via-[#071014]/82 to-[#071014]/30 rtl:bg-gradient-to-l" /><div className="absolute inset-0 bg-gradient-to-t from-[#071014]/80 to-transparent" /><div className="relative flex min-h-[64px] items-center justify-between gap-4"><div className="min-w-0"><h1 className="text-[23px] font-extrabold leading-tight tracking-tight sm:text-[29px]">{t("dashboard.greeting", { name: user?.name?.split(" ")[0] ?? "Owner" })}</h1><p className="mt-1.5 text-xs leading-relaxed text-white/75 sm:mt-2 sm:text-sm">{t("dashboard.subtitle")}</p></div><div className="hidden max-w-48 text-end lg:block"><p className="text-2xl font-black italic uppercase leading-[.95] text-white/80">Fitness<br /><span className="text-white">Beyond Limits</span></p><span className="mt-2 inline-block h-0.5 w-10 bg-primary" /></div></div></section>
    {user?.role === "OWNER" && <SectionSelector value={section} onChange={setSection} />}
    {ownerSection === "all" && (dashboard.unclassifiedMembers ?? 0) > 0 && <p className="rounded-xl border border-warning/20 bg-warning/[.06] px-3 py-2 text-[10px] text-warning">{t("dashboard.unclassifiedWarning", { count: dashboard.unclassifiedMembers ?? 0 })}</p>}
    <section className="grid grid-cols-2 gap-2 sm:gap-3 xl:grid-cols-3 2xl:grid-cols-4">
      <StatCard icon={<Users />} value={dashboard.totalMembers ?? 0} label={memberLabel} change={0} detail={t("dashboard.nonArchivedMembers")} tone="blue" />
      <StatCard icon={<Users />} value={dashboard.activeMembers} label={activeLabel} change={dashboard.activeMembersChange} detail={t("dashboard.currentlyActive")} />
      <StatCard icon={<Clock3 />} value={dashboard.expiringSoon} label={t("dashboard.expiringSoon")} change={dashboard.expiringSoonChange} detail={t("dashboard.next30Days")} tone="amber" />
      <StatCard icon={<AlertTriangle />} value={dashboard.paymentDueMembers ?? dashboard.unpaidFees} label={t("dashboard.paymentDue")} change={dashboard.unpaidFeesChange} detail={t("dashboard.balanceDue")} tone="red" />
      <StatCard icon={<Banknote />} value={dashboard.revenueToday ?? 0} label={t("dashboard.todayRevenue")} change={0} detail={t("dashboard.successfulPaymentsToday")} tone="blue" currency />
      <StatCard icon={<Banknote />} value={dashboard.monthlyRevenue} label={t("dashboard.monthlyRevenue")} change={dashboard.revenueChange} detail={dashboard.businessCycleLabel ? `Cycle: ${dashboard.businessCycleLabel}` : "10th–9th business cycle"} tone="blue" currency />
      <StatCard icon={<UserPlus />} value={dashboard.newMembers ?? 0} label={t("dashboard.newMembers")} change={0} detail={t("dashboard.thisBusinessCycle")} tone="purple" />
      <StatCard icon={<MessageSquareText />} value={dashboard.pendingComplaints ?? 0} label={t("dashboard.complaints")} change={0} detail={t("dashboard.openComplaints")} tone="purple" />
    </section>
    {ownerSection !== "all" && <p className="rounded-xl border border-info/15 bg-info/[.05] px-3 py-2 text-[10px] text-secondary">{t("dashboard.gymWideExpenseNote")}</p>}
    <section className="grid gap-2.5 sm:gap-3 xl:grid-cols-3">
      <ChartCard title={t("dashboard.monthlyRevenueChart")} icon={<BarChart3 />} actions={filter}><div className="dashboard-chart h-[176px] sm:h-[205px]" role="img" aria-label="Monthly revenue area chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={dashboard.trend} margin={{ top: 8, right: 8, left: -12, bottom: 0 }}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#32E875" stopOpacity={0.38} /><stop offset="100%" stopColor="#32E875" stopOpacity={0.015} /></linearGradient></defs><CartesianGrid stroke="#344047" strokeOpacity={0.32} strokeDasharray="2 2" vertical /><XAxis dataKey="label" tick={{ fill: "#93A1AA", fontSize: 10 }} axisLine={{ stroke: "#344047" }} tickLine={false} /><YAxis tick={{ fill: "#93A1AA", fontSize: 9 }} axisLine={false} tickLine={false} tickFormatter={(value) => `${Math.round(Number(value) / 1000)}k`} /><Tooltip content={<ChartTooltip />} /><Area type="monotone" dataKey="revenue" name={t("dashboard.revenue")} stroke="#32E875" strokeWidth={2.25} fill="url(#revenueFill)" dot={{ r: 2.5, fill: "#32E875", strokeWidth: 0 }} activeDot={{ r: 4, stroke: "#071014", strokeWidth: 2 }} /></AreaChart></ResponsiveContainer></div></ChartCard>
      <ChartCard title={t("dashboard.revenueExpenses")} icon={<BarChart3 />} actions={filter}><div className="dashboard-chart dashboard-revenue-expenses h-[176px] sm:h-[205px]" role="img" aria-label="Revenue and expenses grouped bar chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={dashboard.trend} margin={{ top: 8, right: 8, left: -12, bottom: 0 }}><CartesianGrid stroke="#344047" strokeOpacity={0.32} strokeDasharray="2 2" vertical={false} /><XAxis dataKey="label" tick={{ fill: "#93A1AA", fontSize: 10 }} axisLine={{ stroke: "#344047" }} tickLine={false} /><YAxis tick={{ fill: "#93A1AA", fontSize: 9 }} axisLine={false} tickLine={false} tickFormatter={(value) => `${Math.round(Number(value) / 1000)}k`} /><Tooltip content={<ChartTooltip />} /><Legend wrapperStyle={{ fontSize: 10, color: "#93A1AA" }} /><Bar dataKey="revenue" name={t("dashboard.revenue")} fill="#32E875" radius={[3, 3, 0, 0]} maxBarSize={18} /><Bar dataKey="expenses" name={t("dashboard.expenses")} fill="#93A1AA" radius={[3, 3, 0, 0]} maxBarSize={18} /></BarChart></ResponsiveContainer></div></ChartCard>
      {dashboard.profitAvailable ? <ChartCard title={t("dashboard.profitTrend")} icon={<TrendingUp />} actions={filter}><div className="dashboard-chart h-[176px] sm:h-[205px]" role="img" aria-label="Net profit line chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={dashboard.trend} margin={{ top: 8, right: 8, left: -12, bottom: 0 }}><defs><linearGradient id="profitFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#32E875" stopOpacity={0.28} /><stop offset="100%" stopColor="#32E875" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#344047" strokeOpacity={0.32} strokeDasharray="2 2" /><XAxis dataKey="label" tick={{ fill: "#93A1AA", fontSize: 10 }} axisLine={{ stroke: "#344047" }} tickLine={false} /><YAxis tick={{ fill: "#93A1AA", fontSize: 9 }} axisLine={false} tickLine={false} tickFormatter={(value) => `${Math.round(Number(value) / 1000)}k`} /><Tooltip content={<ChartTooltip />} /><Area type="monotone" dataKey="profit" name={t("dashboard.profit")} stroke="#32E875" strokeWidth={2.25} fill="url(#profitFill)" dot={{ r: 2.5, fill: "#32E875" }} /></AreaChart></ResponsiveContainer></div></ChartCard> : <ChartCard title={t("dashboard.profitTrend")} icon={<TrendingUp />}><div className="flex h-[176px] items-center justify-center px-6 text-center sm:h-[205px]"><div><TrendingUp className="mx-auto size-8 text-muted" /><p className="mt-3 text-xs font-semibold text-secondary">{t("dashboard.profitWholeGymOnly")}</p><p className="mt-1 text-[10px] leading-relaxed text-muted">{t("dashboard.profitUnavailableReason")}</p></div></div></ChartCard>}
    </section>
    <section className="grid gap-2.5 sm:gap-3 xl:grid-cols-2"><DonutPanel title={t("dashboard.membershipStatus")} data={dashboard.membershipStatus} totalLabel={t("dashboard.total")} /><DonutPanel title={t("dashboard.paymentStatus")} data={dashboard.paymentStatus} totalLabel={t("dashboard.total")} /></section>
    <section className="grid gap-2.5 sm:gap-3 xl:grid-cols-3">
      <ChartCard title={t("dashboard.newMembers")} icon={<UserPlus />} actions={filter} className="xl:col-span-3"><div className="dashboard-chart dashboard-new-members h-[176px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={dashboard.trend} margin={{ top: 4, right: 10, left: -24, bottom: 0 }}><CartesianGrid stroke="#344047" strokeOpacity={0.3} strokeDasharray="2 2" vertical={false} /><XAxis dataKey="label" tick={{ fill: "#93A1AA", fontSize: 10 }} tickLine={false} axisLine={{ stroke: "#344047" }} /><YAxis allowDecimals={false} tick={{ fill: "#93A1AA", fontSize: 9 }} tickLine={false} axisLine={false} /><Tooltip /><Bar dataKey="newMembers" name="New members" fill="#38A9FF" radius={[4, 4, 0, 0]} maxBarSize={32} /></BarChart></ResponsiveContainer></div></ChartCard>
    </section>
    <section className="grid gap-3 xl:grid-cols-3">
      <PreviewCard title={t("dashboard.recentMembers")} href="/members" compactMobile><div className="hidden overflow-x-auto sm:block"><table className="w-full text-start text-[10px]"><thead><tr className="bg-white/[.055] text-secondary"><th className="rounded-s-md px-2 py-2 font-medium">{t("common.name")}</th><th className="px-2 py-2 font-medium">{t("members.plan")}</th><th className="px-2 py-2 font-medium">{t("members.joinDate")}</th><th className="px-2 py-2 font-medium">{t("members.expiryDate")}</th><th className="rounded-e-md px-2 py-2 font-medium">{t("common.status")}</th></tr></thead><tbody>{dashboard.recentMembers.map((member) => <tr key={member.id} className="border-b border-white/[.055]"><td className="px-2 py-2 font-medium text-foreground">{member.fullName}</td><td className="px-2 py-2 text-secondary">{member.planName}</td><td className="px-2 py-2 text-secondary">{formatDate(member.joinDate, locale)}</td><td className="px-2 py-2 text-secondary">{formatDate(member.expiryDate, locale)}</td><td className="px-2 py-2"><StatusBadge status={member.membershipStatus} /></td></tr>)}</tbody></table></div><MobilePreview compact items={dashboard.recentMembers.map((member) => ({ id: member.id, title: member.fullName, subtitle: `${member.planName} · ${formatDate(member.joinDate, locale)} → ${formatDate(member.expiryDate, locale)}`, status: member.membershipStatus }))} /></PreviewCard>
      <PreviewCard title={t("dashboard.recentPayments")} href="/payments" compactMobile><div className="hidden overflow-x-auto sm:block"><table className="w-full text-start text-[10px]"><thead><tr className="bg-white/[.055] text-secondary"><th className="rounded-s-md px-2 py-2 font-medium">{t("common.date")}</th><th className="px-2 py-2 font-medium">{t("payments.member")}</th><th className="px-2 py-2 font-medium">{t("common.amount")}</th><th className="px-2 py-2 font-medium">{t("payments.method")}</th><th className="rounded-e-md px-2 py-2 font-medium">{t("common.status")}</th></tr></thead><tbody>{dashboard.recentPayments.map((payment) => <tr key={payment.id} className="border-b border-white/[.055]"><td className="px-2 py-2 text-secondary">{formatDate(payment.date, locale)}</td><td className="px-2 py-2 font-medium text-foreground">{payment.memberName}</td><td className="px-2 py-2 text-foreground">{formatCurrency(payment.amountPaid, locale)}</td><td className="px-2 py-2 text-secondary">{payment.method}</td><td className="px-2 py-2"><StatusBadge status={payment.status} /></td></tr>)}</tbody></table></div><MobilePreview compact items={dashboard.recentPayments.map((payment) => ({ id: payment.id, title: payment.memberName, subtitle: `${formatDate(payment.date, locale)} · ${payment.method} · ${formatCurrency(payment.amountPaid, locale)}`, status: payment.status }))} /></PreviewCard>
      <PreviewCard title={t("dashboard.recentExpenses")} href="/expenses"><div className="hidden overflow-x-auto sm:block"><table className="w-full text-start text-[10px]"><thead><tr className="bg-white/[.055] text-secondary"><th className="rounded-s-md px-2 py-2 font-medium">{t("common.date")}</th><th className="px-2 py-2 font-medium">{t("expenses.category")}</th><th className="px-2 py-2 font-medium">{t("common.amount")}</th><th className="rounded-e-md px-2 py-2 font-medium">{t("expenses.addedBy")}</th></tr></thead><tbody>{dashboard.recentExpenses.map((expense) => <tr key={expense.id} className="border-b border-white/[.055]"><td className="px-2 py-2 text-secondary">{formatDate(expense.date, locale)}</td><td className="px-2 py-2 font-medium text-foreground">{expense.category}</td><td className="px-2 py-2 text-foreground">{formatCurrency(expense.amount, locale)}</td><td className="px-2 py-2 text-secondary">{expense.addedBy ?? "—"}</td></tr>)}</tbody></table></div><MobilePreview items={dashboard.recentExpenses.map((expense) => ({ id: expense.id, title: expense.category, subtitle: `${formatDate(expense.date, locale)} · ${formatCurrency(expense.amount, locale)}` }))} /></PreviewCard>
    </section>
    {error && <p className="text-center text-[10px] text-warning">Some data may be stale. {error.message}</p>}
  </div>;
}

function PreviewCard({ title, href, children, compactMobile = false }: { title: string; href: string; children: ReactNode; compactMobile?: boolean }) { const { t } = useLocale(); return <Card className={cn("min-w-0", compactMobile ? "p-2.5 sm:p-3" : "p-3")}><div className={cn("flex items-center justify-between gap-3", compactMobile ? "mb-1.5 sm:mb-2" : "mb-2")}><h2 className="text-xs font-bold">{title}</h2><Link href={href} className="text-[10px] font-semibold text-primary hover:text-primary-hover">{t("common.viewAll")}</Link></div>{children}</Card>; }
function MobilePreview({ items, compact = false }: { items: Array<{ id: string; title: string; subtitle: string; status?: string }>; compact?: boolean }) { return <div className="divide-y divide-white/[.055] sm:hidden">{items.map((item) => <div key={item.id} className={cn("flex items-center justify-between", compact ? "gap-2 py-1.5 [&>span]:px-1.5" : "gap-3 py-2")}><div className="min-w-0"><p className="truncate text-xs font-medium">{item.title}</p><p className={cn("line-clamp-2 text-[10px] text-muted", compact ? "mt-px leading-snug" : "mt-0.5 leading-relaxed")}>{item.subtitle}</p></div>{item.status && <StatusBadge status={item.status} />}</div>)}</div>; }
