"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import {
  AlertTriangle, ArrowDownRight, ArrowUpRight, Banknote, BarChart3, Clock3, CreditCard,
  ReceiptText, TrendingUp, UserPlus, Users,
} from "lucide-react";
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, Pie, PieChart,
  ResponsiveContainer, Tooltip, XAxis, YAxis,
} from "recharts";
import { api } from "@/services";
import { cn, formatCurrency, formatDate } from "@/lib/utils";
import { useApiQuery } from "@/hooks/use-api-query";
import { useLocale } from "@/components/locale-provider";
import { useAuth } from "@/components/auth-provider";
import { Card } from "@/components/ui/card";
import { Select } from "@/components/ui/form-controls";
import { ErrorState, LoadingState } from "@/components/ui/states";
import { StatusBadge } from "@/components/ui/status-badge";
import type { DashboardData, DistributionPoint } from "@/types/api";

const colors = ["#32E875", "#38A9FF", "#9565F6", "#F5B942", "#FF5252", "#93A1AA"];

function StatCard({ icon, value, label, change, detail, tone = "green", currency }: { icon: ReactNode; value: number; label: string; change: number; detail: string; tone?: "green" | "amber" | "red" | "blue" | "purple"; currency?: boolean }) {
  const { locale } = useLocale(); const positive = change >= 0;
  const toneClasses = { green: "border-primary/30 from-primary/[.10] text-primary", amber: "border-warning/30 from-warning/[.10] text-warning", red: "border-danger/30 from-danger/[.10] text-danger", blue: "border-info/30 from-info/[.10] text-info", purple: "border-purple/30 from-purple/[.10] text-purple" };
  return <Card className={cn("group relative min-h-[132px] overflow-hidden border bg-gradient-to-br to-transparent p-4 transition hover:-translate-y-0.5 hover:border-opacity-70", toneClasses[tone])}><div className="absolute -end-10 -top-10 size-24 rounded-full bg-current opacity-[.035] blur-xl" /><div className="relative flex h-full flex-col"><div className="flex size-10 items-center justify-center rounded-xl bg-current/15 shadow-[inset_0_0_0_1px_currentColor] [&>svg]:size-5">{icon}</div><div className="mt-3 flex items-end justify-between gap-2"><div className="min-w-0"><p className="truncate text-[22px] font-extrabold leading-none tracking-tight text-foreground">{currency ? formatCurrency(value, locale) : new Intl.NumberFormat(locale === "ur" ? "ur-PK" : "en-PK").format(value)}</p><p className="mt-2 text-xs font-medium text-white/85">{label}</p></div><span className={cn("mb-0.5 flex shrink-0 items-center gap-0.5 text-[10px] font-bold", positive ? "text-primary" : "text-danger")}>{positive ? <ArrowUpRight className="size-3.5" /> : <ArrowDownRight className="size-3.5" />}{Math.abs(change)}%</span></div><p className="mt-1 text-[10px] text-muted">{detail}</p></div></Card>;
}

function ChartCard({ title, icon, actions, children, className }: { title: string; icon: ReactNode; actions?: ReactNode; children: ReactNode; className?: string }) {
  return <Card className={cn("min-w-0 overflow-hidden p-3.5", className)}><div className="mb-3 flex min-h-8 items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-2 text-sm font-bold"><span className="text-foreground [&>svg]:size-4">{icon}</span><h2 className="truncate">{title}</h2></div>{actions}</div>{children}</Card>;
}

function ChartTooltip({ active, payload, label, currency = true }: { active?: boolean; payload?: Array<{ color?: string; name?: string; value?: number }>; label?: string; currency?: boolean }) {
  const { locale } = useLocale(); if (!active || !payload?.length) return null;
  return <div className="rounded-lg border border-white/10 bg-elevated/95 px-3 py-2 shadow-xl backdrop-blur"><p className="mb-1 text-[10px] font-semibold text-secondary">{label}</p>{payload.map((entry) => <div key={entry.name} className="flex min-w-32 items-center justify-between gap-4 text-[10px]"><span className="flex items-center gap-1.5 text-secondary"><span className="size-1.5 rounded-full" style={{ background: entry.color }} />{entry.name}</span><strong className="text-foreground">{currency ? formatCurrency(Number(entry.value), locale) : new Intl.NumberFormat(locale === "ur" ? "ur-PK" : "en-PK").format(Number(entry.value))}</strong></div>)}</div>;
}

function DonutPanel({ title, data, totalLabel = "Total", pie = false }: { title: string; data: DistributionPoint[]; totalLabel?: string; pie?: boolean }) {
  const total = data.reduce((sum, item) => sum + item.value, 0);
  return <ChartCard title={title} icon={<CreditCard />}><div className="grid min-h-[130px] grid-cols-[minmax(120px,.75fr)_1.2fr] items-center gap-2"><div className="relative h-[125px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={pie ? 0 : 39} outerRadius={56} paddingAngle={pie ? 0 : 1} stroke="none" isAnimationActive>{data.map((_, index) => <Cell key={index} fill={colors[index % colors.length]} />)}</Pie><Tooltip content={<ChartTooltip currency={false} />} /></PieChart></ResponsiveContainer>{!pie && <div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="text-[10px] text-secondary">{totalLabel}</span><strong className="text-xl font-extrabold">{total}</strong></div>}</div><div className="space-y-2.5">{data.map((item, index) => <div key={item.name} className="grid grid-cols-[auto_1fr_auto] items-center gap-2 text-[10px]"><span className="size-2.5 rounded-full" style={{ backgroundColor: colors[index % colors.length] }} /><span className="truncate text-secondary">{item.name}</span><strong className="whitespace-nowrap text-foreground">{item.value} <span className="font-normal text-muted">({total ? Math.round(item.value / total * 100) : 0}%)</span></strong></div>)}</div></div></ChartCard>;
}

function DashboardSkeleton() {
  return <div className="space-y-3"><div className="h-28 animate-pulse rounded-panel bg-white/[.045]" /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-32 animate-pulse rounded-panel bg-white/[.045]" />)}</div><div className="grid gap-3 xl:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-60 animate-pulse rounded-panel bg-white/[.045]" />)}</div></div>;
}

export function DashboardPage() {
  const { t, locale } = useLocale(); const { user } = useAuth(); const [range, setRange] = useState("6months");
  const { data, error, loading, reload } = useApiQuery(() => api.dashboard(range), [range]);
  if (loading && !data) return <DashboardSkeleton />;
  if (error && !data) return <ErrorState title="Could not load dashboard" message={error.message} onRetry={reload} />;
  const dashboard = data as DashboardData;
  const filter = <Select value={range} onChange={(event) => setRange(event.target.value)} className="h-8 w-auto min-w-28 py-0 text-[10px]" aria-label="Chart period"><option value="6months">{t("dashboard.last6Months")}</option><option value="12m">{t("dashboard.last12Months")}</option><option value="year">{t("dashboard.thisYear")}</option></Select>;
  return <div className="space-y-3 animate-fade-up">
    <section className="relative min-h-[112px] overflow-hidden rounded-panel border border-white/[.07] bg-[url('/images/fitx-hero.png')] bg-cover bg-[center_38%] px-5 py-6 sm:px-6"><div className="absolute inset-0 bg-gradient-to-r from-[#060b0e] via-[#071014]/82 to-[#071014]/30 rtl:bg-gradient-to-l" /><div className="absolute inset-0 bg-gradient-to-t from-[#071014]/80 to-transparent" /><div className="relative flex min-h-[64px] items-center justify-between gap-4"><div><h1 className="text-[25px] font-extrabold leading-tight tracking-tight sm:text-[29px]">{t("dashboard.greeting", { name: user?.name?.split(" ")[0] ?? "Owner" })}</h1><p className="mt-2 text-sm text-white/75">{t("dashboard.subtitle")}</p></div><div className="hidden max-w-48 text-end lg:block"><p className="text-2xl font-black italic uppercase leading-[.95] text-white/80">Fitness<br /><span className="text-white">Beyond Limits</span></p><span className="mt-2 inline-block h-0.5 w-10 bg-primary" /></div></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">
      <StatCard icon={<Users />} value={dashboard.activeMembers} label={t("dashboard.activeMembers")} change={dashboard.activeMembersChange} detail={t("dashboard.vsLastMonth")} />
      <StatCard icon={<Clock3 />} value={dashboard.expiringSoon} label={t("dashboard.expiringSoon")} change={dashboard.expiringSoonChange} detail={t("dashboard.next30Days")} tone="amber" />
      <StatCard icon={<AlertTriangle />} value={dashboard.unpaidFees} label={t("dashboard.unpaidFees")} change={dashboard.unpaidFeesChange} detail={t("dashboard.totalOverdue")} tone="red" />
      <StatCard icon={<Banknote />} value={dashboard.monthlyRevenue} label={t("dashboard.monthlyRevenue")} change={dashboard.revenueChange} detail={t("dashboard.vsLastMonth")} tone="blue" currency />
      <StatCard icon={<ReceiptText />} value={dashboard.monthlyExpenses} label={t("dashboard.expenses")} change={dashboard.expensesChange} detail={t("dashboard.vsLastMonth")} tone="purple" currency />
      <StatCard icon={<TrendingUp />} value={dashboard.netProfit} label={t("dashboard.netProfit")} change={dashboard.profitChange} detail={t("dashboard.vsLastMonth")} currency />
    </section>
    <section className="grid gap-3 xl:grid-cols-3">
      <ChartCard title={t("dashboard.monthlyRevenueChart")} icon={<BarChart3 />} actions={filter}><div className="h-[205px]" role="img" aria-label="Monthly revenue area chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={dashboard.trend} margin={{ top: 8, right: 8, left: -12, bottom: 0 }}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#32E875" stopOpacity={0.38} /><stop offset="100%" stopColor="#32E875" stopOpacity={0.015} /></linearGradient></defs><CartesianGrid stroke="#344047" strokeOpacity={0.32} strokeDasharray="2 2" vertical /><XAxis dataKey="label" tick={{ fill: "#93A1AA", fontSize: 10 }} axisLine={{ stroke: "#344047" }} tickLine={false} /><YAxis tick={{ fill: "#93A1AA", fontSize: 9 }} axisLine={false} tickLine={false} tickFormatter={(value) => `${Math.round(Number(value) / 1000)}k`} /><Tooltip content={<ChartTooltip />} /><Area type="monotone" dataKey="revenue" name={t("dashboard.revenue")} stroke="#32E875" strokeWidth={2.25} fill="url(#revenueFill)" dot={{ r: 2.5, fill: "#32E875", strokeWidth: 0 }} activeDot={{ r: 4, stroke: "#071014", strokeWidth: 2 }} /></AreaChart></ResponsiveContainer></div></ChartCard>
      <ChartCard title={t("dashboard.revenueExpenses")} icon={<BarChart3 />} actions={filter}><div className="h-[205px]" role="img" aria-label="Revenue and expenses grouped bar chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={dashboard.trend} margin={{ top: 8, right: 8, left: -12, bottom: 0 }}><CartesianGrid stroke="#344047" strokeOpacity={0.32} strokeDasharray="2 2" vertical={false} /><XAxis dataKey="label" tick={{ fill: "#93A1AA", fontSize: 10 }} axisLine={{ stroke: "#344047" }} tickLine={false} /><YAxis tick={{ fill: "#93A1AA", fontSize: 9 }} axisLine={false} tickLine={false} tickFormatter={(value) => `${Math.round(Number(value) / 1000)}k`} /><Tooltip content={<ChartTooltip />} /><Legend wrapperStyle={{ fontSize: 10, color: "#93A1AA" }} /><Bar dataKey="revenue" name={t("dashboard.revenue")} fill="#32E875" radius={[3, 3, 0, 0]} maxBarSize={18} /><Bar dataKey="expenses" name={t("dashboard.expenses")} fill="#93A1AA" radius={[3, 3, 0, 0]} maxBarSize={18} /></BarChart></ResponsiveContainer></div></ChartCard>
      <ChartCard title={t("dashboard.profitTrend")} icon={<TrendingUp />} actions={filter}><div className="h-[205px]" role="img" aria-label="Net profit line chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={dashboard.trend} margin={{ top: 8, right: 8, left: -12, bottom: 0 }}><defs><linearGradient id="profitFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#32E875" stopOpacity={0.28} /><stop offset="100%" stopColor="#32E875" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#344047" strokeOpacity={0.32} strokeDasharray="2 2" /><XAxis dataKey="label" tick={{ fill: "#93A1AA", fontSize: 10 }} axisLine={{ stroke: "#344047" }} tickLine={false} /><YAxis tick={{ fill: "#93A1AA", fontSize: 9 }} axisLine={false} tickLine={false} tickFormatter={(value) => `${Math.round(Number(value) / 1000)}k`} /><Tooltip content={<ChartTooltip />} /><Area type="monotone" dataKey="profit" name={t("dashboard.profit")} stroke="#32E875" strokeWidth={2.25} fill="url(#profitFill)" dot={{ r: 2.5, fill: "#32E875" }} /></AreaChart></ResponsiveContainer></div></ChartCard>
    </section>
    <section className="grid gap-3 xl:grid-cols-3"><DonutPanel title={t("dashboard.membershipStatus")} data={dashboard.membershipStatus} totalLabel={t("dashboard.total")} /><DonutPanel title={t("dashboard.paymentStatus")} data={dashboard.paymentStatus} totalLabel={t("dashboard.total")} /><DonutPanel title={t("dashboard.membershipPlans")} data={dashboard.planDistribution} totalLabel={t("dashboard.total")} pie /></section>
    <section className="grid gap-3 xl:grid-cols-3">
      <ChartCard title={t("dashboard.newMembers")} icon={<UserPlus />} actions={filter} className="xl:col-span-3"><div className="h-44"><ResponsiveContainer width="100%" height="100%"><BarChart data={dashboard.trend} margin={{ top: 4, right: 10, left: -24, bottom: 0 }}><CartesianGrid stroke="#344047" strokeOpacity={0.3} strokeDasharray="2 2" vertical={false} /><XAxis dataKey="label" tick={{ fill: "#93A1AA", fontSize: 10 }} tickLine={false} axisLine={{ stroke: "#344047" }} /><YAxis allowDecimals={false} tick={{ fill: "#93A1AA", fontSize: 9 }} tickLine={false} axisLine={false} /><Tooltip /><Bar dataKey="newMembers" name="New members" fill="#38A9FF" radius={[4, 4, 0, 0]} maxBarSize={32} /></BarChart></ResponsiveContainer></div></ChartCard>
    </section>
    <section className="grid gap-3 xl:grid-cols-3">
      <PreviewCard title={t("dashboard.recentMembers")} href="/members"><div className="hidden overflow-x-auto sm:block"><table className="w-full text-start text-[10px]"><thead><tr className="bg-white/[.055] text-secondary"><th className="rounded-s-md px-2 py-2 font-medium">{t("common.name")}</th><th className="px-2 py-2 font-medium">{t("members.plan")}</th><th className="px-2 py-2 font-medium">{t("members.joinDate")}</th><th className="px-2 py-2 font-medium">{t("members.expiryDate")}</th><th className="rounded-e-md px-2 py-2 font-medium">{t("common.status")}</th></tr></thead><tbody>{dashboard.recentMembers.map((member) => <tr key={member.id} className="border-b border-white/[.055]"><td className="px-2 py-2 font-medium text-foreground">{member.fullName}</td><td className="px-2 py-2 text-secondary">{member.planName}</td><td className="px-2 py-2 text-secondary">{formatDate(member.joinDate, locale)}</td><td className="px-2 py-2 text-secondary">{formatDate(member.expiryDate, locale)}</td><td className="px-2 py-2"><StatusBadge status={member.membershipStatus} /></td></tr>)}</tbody></table></div><MobilePreview items={dashboard.recentMembers.map((member) => ({ id: member.id, title: member.fullName, subtitle: `${member.planName} · ${formatDate(member.joinDate, locale)} → ${formatDate(member.expiryDate, locale)}`, status: member.membershipStatus }))} /></PreviewCard>
      <PreviewCard title={t("dashboard.recentPayments")} href="/payments"><div className="hidden overflow-x-auto sm:block"><table className="w-full text-start text-[10px]"><thead><tr className="bg-white/[.055] text-secondary"><th className="rounded-s-md px-2 py-2 font-medium">{t("common.date")}</th><th className="px-2 py-2 font-medium">{t("payments.member")}</th><th className="px-2 py-2 font-medium">{t("common.amount")}</th><th className="px-2 py-2 font-medium">{t("payments.method")}</th><th className="rounded-e-md px-2 py-2 font-medium">{t("common.status")}</th></tr></thead><tbody>{dashboard.recentPayments.map((payment) => <tr key={payment.id} className="border-b border-white/[.055]"><td className="px-2 py-2 text-secondary">{formatDate(payment.date, locale)}</td><td className="px-2 py-2 font-medium text-foreground">{payment.memberName}</td><td className="px-2 py-2 text-foreground">{formatCurrency(payment.amountPaid, locale)}</td><td className="px-2 py-2 text-secondary">{payment.method}</td><td className="px-2 py-2"><StatusBadge status={payment.status} /></td></tr>)}</tbody></table></div><MobilePreview items={dashboard.recentPayments.map((payment) => ({ id: payment.id, title: payment.memberName, subtitle: `${formatDate(payment.date, locale)} · ${payment.method} · ${formatCurrency(payment.amountPaid, locale)}`, status: payment.status }))} /></PreviewCard>
      <PreviewCard title={t("dashboard.recentExpenses")} href="/expenses"><div className="hidden overflow-x-auto sm:block"><table className="w-full text-start text-[10px]"><thead><tr className="bg-white/[.055] text-secondary"><th className="rounded-s-md px-2 py-2 font-medium">{t("common.date")}</th><th className="px-2 py-2 font-medium">{t("expenses.category")}</th><th className="px-2 py-2 font-medium">{t("common.amount")}</th><th className="rounded-e-md px-2 py-2 font-medium">{t("expenses.addedBy")}</th></tr></thead><tbody>{dashboard.recentExpenses.map((expense) => <tr key={expense.id} className="border-b border-white/[.055]"><td className="px-2 py-2 text-secondary">{formatDate(expense.date, locale)}</td><td className="px-2 py-2 font-medium text-foreground">{expense.category}</td><td className="px-2 py-2 text-foreground">{formatCurrency(expense.amount, locale)}</td><td className="px-2 py-2 text-secondary">{expense.addedBy ?? "—"}</td></tr>)}</tbody></table></div><MobilePreview items={dashboard.recentExpenses.map((expense) => ({ id: expense.id, title: expense.category, subtitle: `${formatDate(expense.date, locale)} · ${formatCurrency(expense.amount, locale)}` }))} /></PreviewCard>
    </section>
    {error && <p className="text-center text-[10px] text-warning">Some data may be stale. {error.message}</p>}
  </div>;
}

function PreviewCard({ title, href, children }: { title: string; href: string; children: ReactNode }) { const { t } = useLocale(); return <Card className="min-w-0 p-3"><div className="mb-2 flex items-center justify-between gap-3"><h2 className="text-xs font-bold">{title}</h2><Link href={href} className="text-[10px] font-semibold text-primary hover:text-primary-hover">{t("common.viewAll")}</Link></div>{children}</Card>; }
function MobilePreview({ items }: { items: Array<{ id: string; title: string; subtitle: string; status?: string }> }) { return <div className="divide-y divide-white/[.055] sm:hidden">{items.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 py-2"><div><p className="text-xs font-medium">{item.title}</p><p className="mt-0.5 text-[10px] text-muted">{item.subtitle}</p></div>{item.status && <StatusBadge status={item.status} />}</div>)}</div>; }
