"use client";

import { useEffect, useMemo, useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { api } from "@/services";
import { getErrorMessage, membershipEndDate, todayInput } from "@/lib/utils";
import { useLocale } from "@/components/locale-provider";
import { useToast } from "@/components/toast-provider";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Field, Input, Select, Textarea } from "@/components/ui/form-controls";
import type { LookupItem, Member, MemberInput, MembershipPlan } from "@/types/api";

interface MemberFormValues {
  fullName: string; phone: string; email: string; cnic: string; gender: string; dateOfBirth: string; address: string;
  membershipPlanId: string; joiningDate: string; membershipStartDate: string; membershipFee: number; discount: number;
  amountPaid: number; paymentMethodId: string; notes: string;
}

export function MemberFormDialog({ open, onClose, member, onSaved }: { open: boolean; onClose: () => void; member?: Member | null; onSaved: () => void }) {
  const { t } = useLocale(); const { toast } = useToast(); const [plans, setPlans] = useState<MembershipPlan[]>([]); const [methods, setMethods] = useState<LookupItem[]>([]); const [serverError, setServerError] = useState("");
  const editing = Boolean(member);
  const { register, handleSubmit, reset, control, setValue, formState: { errors, isSubmitting } } = useForm<MemberFormValues>();
  useEffect(() => { if (!open) return; Promise.all([api.plans.list(), api.payments.methods()]).then(([nextPlans, nextMethods]) => { setPlans(nextPlans.filter((plan) => plan.isActive)); setMethods(nextMethods.filter((method) => method.isActive !== false)); }).catch((error) => setServerError(getErrorMessage(error))); }, [open]);
  useEffect(() => { if (!open) return; const today = todayInput(); reset({ fullName: member?.fullName ?? "", phone: member?.phone ?? "", email: member?.email ?? "", cnic: member?.cnic ?? "", gender: member?.gender ?? "", dateOfBirth: member?.dateOfBirth?.slice(0, 10) ?? "", address: member?.address ?? "", membershipPlanId: member?.planId ?? "", joiningDate: member?.joinDate?.slice(0, 10) ?? today, membershipStartDate: member?.startDate?.slice(0, 10) ?? today, membershipFee: member?.fee ?? 0, discount: member?.discount ?? 0, amountPaid: 0, paymentMethodId: "", notes: member?.notes ?? "" }); setServerError(""); }, [open, member, reset]);
  const [planId, joiningDate, startDate, watchedFee, watchedDiscount, watchedAmountPaid] = useWatch({ control, name: ["membershipPlanId", "joiningDate", "membershipStartDate", "membershipFee", "discount", "amountPaid"] }); const fee = Number(watchedFee || 0); const discount = Number(watchedDiscount || 0); const amountPaid = Number(watchedAmountPaid || 0);
  const selectedPlan = plans.find((plan) => plan.id === planId);
  useEffect(() => { if (selectedPlan && !editing) setValue("membershipFee", selectedPlan.price); }, [selectedPlan, setValue, editing]);
  const finalFee = Math.max(0, fee - discount); const expiry = useMemo(() => startDate && selectedPlan ? membershipEndDate(startDate, selectedPlan.durationMonths) : "", [startDate, selectedPlan]);
  const submit = async (values: MemberFormValues) => { setServerError(""); try { if (editing && member) { await api.members.update(member.id, values as Partial<MemberInput>); } else { await api.members.create({ ...values, expiryDate: expiry }); } toast(editing ? "Member updated" : "Member added", { description: `${values.fullName} was saved successfully.` }); onSaved(); onClose(); } catch (error) { setServerError(getErrorMessage(error, "Could not save member.")); } };
  return <Dialog open={open} onClose={onClose} title={editing ? "Edit member" : t("members.add")} description={editing ? "Update the member’s personal and contact details." : "Create a profile and first membership. Expiry is calculated from the selected plan."} size="lg" footer={<><Button variant="secondary" type="button" onClick={onClose}>{t("common.cancel")}</Button><Button form="member-form" type="submit" loading={isSubmitting}>{editing ? t("common.save") : t("members.add")}</Button></>}>
    <form id="member-form" onSubmit={handleSubmit(submit)} className="space-y-6" noValidate>{serverError && <div className="rounded-lg border border-danger/25 bg-danger/[.08] p-3 text-xs text-danger" role="alert">{serverError}</div>}<section><h3 className="mb-4 text-xs font-bold uppercase tracking-wider text-primary">Personal details</h3><div className="grid gap-4 sm:grid-cols-2"><Field label={t("members.fullName")} error={errors.fullName?.message} required><Input autoFocus {...register("fullName", { required: t("common.required"), minLength: { value: 2, message: "Use at least 2 characters." } })} /></Field><Field label={t("common.phone")} error={errors.phone?.message} required><Input type="tel" dir="ltr" {...register("phone", { required: t("common.required") })} /></Field><Field label={t("common.email")} error={errors.email?.message}><Input type="email" dir="ltr" {...register("email", { pattern: { value: /^$|^\S+@\S+\.\S+$/, message: "Enter a valid email." } })} /></Field><Field label="CNIC / ID number"><Input dir="ltr" {...register("cnic")} /></Field><Field label="Gender"><Select {...register("gender")}><option value="">Not specified</option><option>Male</option><option>Female</option><option>Other</option></Select></Field><Field label="Date of birth"><Input type="date" max={todayInput()} {...register("dateOfBirth")} /></Field><Field label="Address" className="sm:col-span-2"><Input {...register("address")} /></Field></div></section>
    {!editing && <section><h3 className="mb-4 text-xs font-bold uppercase tracking-wider text-primary">Membership & payment</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label={t("members.plan")} error={errors.membershipPlanId?.message} required><Select {...register("membershipPlanId", { required: t("common.required") })}><option value="">Select plan</option>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</Select></Field><Field label={t("members.joinDate")} error={errors.joiningDate?.message} required><Input type="date" {...register("joiningDate", { required: t("common.required") })} /></Field><Field label={t("members.startDate")} error={errors.membershipStartDate?.message} required><Input type="date" min={joiningDate} {...register("membershipStartDate", { required: t("common.required"), validate: (value) => !joiningDate || value >= joiningDate || "Membership cannot start before the join date." })} /></Field><Field label={t("members.expiryDate")} hint="Calculated automatically"><Input type="date" value={expiry} readOnly disabled /></Field><Field label={t("members.fee")} error={errors.membershipFee?.message} required><Input type="number" min={0} step="1" {...register("membershipFee", { valueAsNumber: true, min: { value: 0, message: "Fee cannot be negative." } })} /></Field><Field label={t("members.discount")} error={errors.discount?.message}><Input type="number" min={0} max={fee} step="1" {...register("discount", { valueAsNumber: true, validate: (value) => value <= fee || "Discount cannot exceed fee." })} /></Field><Field label={t("members.finalFee")}><Input value={finalFee} readOnly disabled /></Field><Field label="Initial amount paid" error={errors.amountPaid?.message}><Input type="number" min={0} max={finalFee} step="1" {...register("amountPaid", { valueAsNumber: true, validate: (value) => value <= finalFee || "Payment cannot exceed final fee." })} /></Field><Field label="Payment method" error={errors.paymentMethodId?.message}><Select {...register("paymentMethodId", { validate: (value) => amountPaid <= 0 || Boolean(value) || "Choose a payment method." })}><option value="">Select method</option>{methods.map((method) => <option key={method.id} value={method.id}>{method.name}</option>)}</Select></Field></div></section>}
    <Field label={t("common.notes")}><Textarea rows={3} placeholder="Optional member or membership notes" {...register("notes")} /></Field></form>
  </Dialog>;
}

interface RenewValues { planId: string; renewalDate: string; membershipFee: number; discount: number; amountPaid: number; paymentMethodId: string; referenceNumber: string; notes: string; }
export function RenewMemberDialog({ open, member, onClose, onSaved }: { open: boolean; member: Member | null; onClose: () => void; onSaved: () => void }) {
  const { t } = useLocale(); const { toast } = useToast(); const [plans, setPlans] = useState<MembershipPlan[]>([]); const [methods, setMethods] = useState<LookupItem[]>([]); const [serverError, setServerError] = useState(""); const { register, handleSubmit, reset, control, setValue, formState: { isSubmitting, errors } } = useForm<RenewValues>();
  useEffect(() => { if (!open) return; Promise.all([api.plans.list(), api.payments.methods()]).then(([p, m]) => { setPlans(p.filter((item) => item.isActive)); setMethods(m.filter((item) => item.isActive !== false)); }).catch((error) => setServerError(getErrorMessage(error))); reset({ planId: member?.planId ?? "", renewalDate: todayInput(), membershipFee: member?.fee ?? 0, discount: 0, amountPaid: 0, paymentMethodId: "", referenceNumber: "", notes: "" }); }, [open, member, reset]);
  const [planId, watchedFee, watchedDiscount, watchedPaid] = useWatch({ control, name: ["planId", "membershipFee", "discount", "amountPaid"] }); const selectedPlan = plans.find((plan) => plan.id === planId); const fee = Number(watchedFee || 0); const discount = Number(watchedDiscount || 0); const paid = Number(watchedPaid || 0); const payable = Math.max(0, fee - discount);
  useEffect(() => { if (selectedPlan) setValue("membershipFee", selectedPlan.price); }, [selectedPlan, setValue]);
  const submit = async (values: RenewValues) => { if (!member) return; setServerError(""); try { await api.members.renew(member.id, values); toast("Membership renewed", { description: `${member.fullName} now has a ${selectedPlan?.name ?? "new"} membership.` }); onSaved(); onClose(); } catch (error) { setServerError(getErrorMessage(error, "Could not renew membership.")); } };
  return <Dialog open={open} onClose={onClose} title={t("members.renew")} description={member ? `${member.fullName} · Current expiry ${member.expiryDate}` : undefined} size="md" footer={<><Button variant="secondary" onClick={onClose}>{t("common.cancel")}</Button><Button form="renew-form" type="submit" loading={isSubmitting}>{t("members.renew")}</Button></>}><form id="renew-form" onSubmit={handleSubmit(submit)} className="grid gap-4 sm:grid-cols-2">{serverError && <p className="rounded-lg border border-danger/25 bg-danger/[.08] p-3 text-xs text-danger sm:col-span-2">{serverError}</p>}<Field label="Previous plan"><Input value={member?.planName ?? ""} disabled /></Field><Field label="Previous expiry"><Input value={member?.expiryDate?.slice(0, 10) ?? ""} disabled /></Field><Field label="New plan" error={errors.planId?.message} required><Select {...register("planId", { required: t("common.required") })}><option value="">Select plan</option>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</Select></Field><Field label="Renewal date" required><Input type="date" {...register("renewalDate", { required: t("common.required") })} /></Field><Field label="Membership fee"><Input type="number" min={0} {...register("membershipFee", { valueAsNumber: true })} /></Field><Field label={t("members.discount")}><Input type="number" min={0} max={fee} {...register("discount", { valueAsNumber: true, validate: (value) => value <= fee || "Discount exceeds fee." })} /></Field><Field label="Amount paid"><Input type="number" min={0} max={payable} {...register("amountPaid", { valueAsNumber: true, validate: (value) => value <= payable || "Payment exceeds payable amount." })} /></Field><Field label="Payment method" error={errors.paymentMethodId?.message}><Select {...register("paymentMethodId", { validate: (value) => paid <= 0 || Boolean(value) || "Choose a payment method." })}><option value="">Select method</option>{methods.map((method) => <option key={method.id} value={method.id}>{method.name}</option>)}</Select></Field><Field label="Reference"><Input {...register("referenceNumber")} /></Field><Field label={t("common.notes")} className="sm:col-span-2"><Textarea {...register("notes")} /></Field></form></Dialog>;
}
